services:
  nats:
    image: nats:latest
    ports:
      - '4222:4222'
      - '8222:8222'
    command: '-js -sd /data'
    volumes:
      - nats_jetstream_data:/data
    container_name: nats-server
    restart: unless-stopped

  app:
    build: .
    depends_on: ['nats']
    ports:
      - '8080:8080'
    restart: unless-stopped
    environment:
      - NATS_URL=${NATS_URL}
      - JS_STREAM_NAME=${JS_STREAM_NAME}
      - JS_STREAM_SUBJECTS=${JS_STREAM_SUBJECTS}
      - JS_RETENTION_HOURS=${JS_RETENTION_HOURS}

volumes:
  nats_jetstream_data:
